// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

//Keep this type insync with real NoteConfig
type NoteConfig struct {
	Editor    string `json:"editor"`
	Location  string `json:"location"`
	Template  string `json:"template"`
	Extension string `json:"extension"`
}