name: Gradle Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - name: Run tests
        run: go test ./...
      - name: Build  tests
        run: go build -C note

